sudo: required

services:
- docker

before_install:
- mkdir -p out
- docker build ./ -t t2-compiler:dev

script:
- docker run --rm -v `pwd`/out:/out t2-compiler:dev serialport@4.0.7 6.5.0 release /out
- test -f out/serialport-4.0.7-Release-node-v48-linux-mipsel.tgz
